// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Bebida_consumo;
import es.uca.iw.hoteloasis.domain.Bebida_consumoDataOnDemand;
import es.uca.iw.hoteloasis.domain.Bebida_consumoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Bebida_consumoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: Bebida_consumoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: Bebida_consumoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: Bebida_consumoIntegrationTest: @Transactional;
    
    @Autowired
    Bebida_consumoDataOnDemand Bebida_consumoIntegrationTest.dod;
    
    @Test
    public void Bebida_consumoIntegrationTest.testCountBebida_consumoes() {
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", dod.getRandomBebida_consumo());
        long count = Bebida_consumo.countBebida_consumoes();
        Assert.assertTrue("Counter for 'Bebida_consumo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testFindBebida_consumo() {
        Bebida_consumo obj = dod.getRandomBebida_consumo();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to provide an identifier", id);
        obj = Bebida_consumo.findBebida_consumo(id);
        Assert.assertNotNull("Find method for 'Bebida_consumo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bebida_consumo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testFindAllBebida_consumoes() {
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", dod.getRandomBebida_consumo());
        long count = Bebida_consumo.countBebida_consumoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bebida_consumo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bebida_consumo> result = Bebida_consumo.findAllBebida_consumoes();
        Assert.assertNotNull("Find all method for 'Bebida_consumo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bebida_consumo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testFindBebida_consumoEntries() {
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", dod.getRandomBebida_consumo());
        long count = Bebida_consumo.countBebida_consumoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bebida_consumo> result = Bebida_consumo.findBebida_consumoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bebida_consumo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bebida_consumo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testFlush() {
        Bebida_consumo obj = dod.getRandomBebida_consumo();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to provide an identifier", id);
        obj = Bebida_consumo.findBebida_consumo(id);
        Assert.assertNotNull("Find method for 'Bebida_consumo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBebida_consumo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Bebida_consumo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testMergeUpdate() {
        Bebida_consumo obj = dod.getRandomBebida_consumo();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to provide an identifier", id);
        obj = Bebida_consumo.findBebida_consumo(id);
        boolean modified =  dod.modifyBebida_consumo(obj);
        Integer currentVersion = obj.getVersion();
        Bebida_consumo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Bebida_consumo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", dod.getRandomBebida_consumo());
        Bebida_consumo obj = dod.getNewTransientBebida_consumo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bebida_consumo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Bebida_consumo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void Bebida_consumoIntegrationTest.testRemove() {
        Bebida_consumo obj = dod.getRandomBebida_consumo();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bebida_consumo' failed to provide an identifier", id);
        obj = Bebida_consumo.findBebida_consumo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Bebida_consumo' with identifier '" + id + "'", Bebida_consumo.findBebida_consumo(id));
    }
    
}
