// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Bebida;
import es.uca.iw.hoteloasis.domain.BebidaDataOnDemand;
import es.uca.iw.hoteloasis.domain.Bebida_consumo;
import es.uca.iw.hoteloasis.domain.Bebida_consumoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect Bebida_consumoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: Bebida_consumoDataOnDemand: @Component;
    
    private Random Bebida_consumoDataOnDemand.rnd = new SecureRandom();
    
    private List<Bebida_consumo> Bebida_consumoDataOnDemand.data;
    
    @Autowired
    BebidaDataOnDemand Bebida_consumoDataOnDemand.bebidaDataOnDemand;
    
    public Bebida_consumo Bebida_consumoDataOnDemand.getNewTransientBebida_consumo(int index) {
        Bebida_consumo obj = new Bebida_consumo();
        setBebida(obj, index);
        setCantidad(obj, index);
        return obj;
    }
    
    public void Bebida_consumoDataOnDemand.setBebida(Bebida_consumo obj, int index) {
        Bebida bebida = bebidaDataOnDemand.getRandomBebida();
        obj.setBebida(bebida);
    }
    
    public void Bebida_consumoDataOnDemand.setCantidad(Bebida_consumo obj, int index) {
        int cantidad = index;
        obj.setCantidad(cantidad);
    }
    
    public Bebida_consumo Bebida_consumoDataOnDemand.getSpecificBebida_consumo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Bebida_consumo obj = data.get(index);
        Long id = obj.getId();
        return Bebida_consumo.findBebida_consumo(id);
    }
    
    public Bebida_consumo Bebida_consumoDataOnDemand.getRandomBebida_consumo() {
        init();
        Bebida_consumo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Bebida_consumo.findBebida_consumo(id);
    }
    
    public boolean Bebida_consumoDataOnDemand.modifyBebida_consumo(Bebida_consumo obj) {
        return false;
    }
    
    public void Bebida_consumoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Bebida_consumo.findBebida_consumoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Bebida_consumo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Bebida_consumo>();
        for (int i = 0; i < 10; i++) {
            Bebida_consumo obj = getNewTransientBebida_consumo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
