// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.CategoriaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CategoriaDataOnDemand_Roo_Configurable {
    
    declare @type: CategoriaDataOnDemand: @Configurable;
    
}
