// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Categoria;
import es.uca.iw.hoteloasis.domain.CategoriaDataOnDemand;
import es.uca.iw.hoteloasis.domain.Hotel;
import es.uca.iw.hoteloasis.domain.HotelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CategoriaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoriaDataOnDemand: @Component;
    
    private Random CategoriaDataOnDemand.rnd = new SecureRandom();
    
    private List<Categoria> CategoriaDataOnDemand.data;
    
    @Autowired
    HotelDataOnDemand CategoriaDataOnDemand.hotelDataOnDemand;
    
    public Categoria CategoriaDataOnDemand.getNewTransientCategoria(int index) {
        Categoria obj = new Categoria();
        setDescripcion(obj, index);
        setHotel(obj, index);
        setNombre(obj, index);
        setPrecio_categoria(obj, index);
        return obj;
    }
    
    public void CategoriaDataOnDemand.setDescripcion(Categoria obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void CategoriaDataOnDemand.setHotel(Categoria obj, int index) {
        Hotel hotel = hotelDataOnDemand.getRandomHotel();
        obj.setHotel(hotel);
    }
    
    public void CategoriaDataOnDemand.setNombre(Categoria obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void CategoriaDataOnDemand.setPrecio_categoria(Categoria obj, int index) {
        double precio_categoria = new Integer(index).doubleValue();
        obj.setPrecio_categoria(precio_categoria);
    }
    
    public Categoria CategoriaDataOnDemand.getSpecificCategoria(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Categoria obj = data.get(index);
        Long id = obj.getId();
        return Categoria.findCategoria(id);
    }
    
    public Categoria CategoriaDataOnDemand.getRandomCategoria() {
        init();
        Categoria obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Categoria.findCategoria(id);
    }
    
    public boolean CategoriaDataOnDemand.modifyCategoria(Categoria obj) {
        return false;
    }
    
    public void CategoriaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Categoria.findCategoriaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Categoria' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Categoria>();
        for (int i = 0; i < 10; i++) {
            Categoria obj = getNewTransientCategoria(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
