// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Categoria;
import es.uca.iw.hoteloasis.domain.CategoriaDataOnDemand;
import es.uca.iw.hoteloasis.domain.Habitacion;
import es.uca.iw.hoteloasis.domain.HabitacionDataOnDemand;
import es.uca.iw.hoteloasis.domain.Habitacion_estado;
import es.uca.iw.hoteloasis.domain.Habitacion_tipo;
import es.uca.iw.hoteloasis.domain.Hotel;
import es.uca.iw.hoteloasis.domain.HotelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect HabitacionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HabitacionDataOnDemand: @Component;
    
    private Random HabitacionDataOnDemand.rnd = new SecureRandom();
    
    private List<Habitacion> HabitacionDataOnDemand.data;
    
    @Autowired
    CategoriaDataOnDemand HabitacionDataOnDemand.categoriaDataOnDemand;
    
    @Autowired
    HotelDataOnDemand HabitacionDataOnDemand.hotelDataOnDemand;
    
    public Habitacion HabitacionDataOnDemand.getNewTransientHabitacion(int index) {
        Habitacion obj = new Habitacion();
        setCategoria(obj, index);
        setEstado(obj, index);
        setHotel(obj, index);
        setNumero(obj, index);
        setTipo(obj, index);
        return obj;
    }
    
    public void HabitacionDataOnDemand.setCategoria(Habitacion obj, int index) {
        Categoria categoria = categoriaDataOnDemand.getRandomCategoria();
        obj.setCategoria(categoria);
    }
    
    public void HabitacionDataOnDemand.setEstado(Habitacion obj, int index) {
        Habitacion_estado estado = Habitacion_estado.class.getEnumConstants()[0];
        obj.setEstado(estado);
    }
    
    public void HabitacionDataOnDemand.setHotel(Habitacion obj, int index) {
        Hotel hotel = hotelDataOnDemand.getRandomHotel();
        obj.setHotel(hotel);
    }
    
    public void HabitacionDataOnDemand.setNumero(Habitacion obj, int index) {
        int numero = index;
        obj.setNumero(numero);
    }
    
    public void HabitacionDataOnDemand.setTipo(Habitacion obj, int index) {
        Habitacion_tipo tipo = Habitacion_tipo.class.getEnumConstants()[0];
        obj.setTipo(tipo);
    }
    
    public Habitacion HabitacionDataOnDemand.getSpecificHabitacion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Habitacion obj = data.get(index);
        Long id = obj.getId();
        return Habitacion.findHabitacion(id);
    }
    
    public Habitacion HabitacionDataOnDemand.getRandomHabitacion() {
        init();
        Habitacion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Habitacion.findHabitacion(id);
    }
    
    public boolean HabitacionDataOnDemand.modifyHabitacion(Habitacion obj) {
        return false;
    }
    
    public void HabitacionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Habitacion.findHabitacionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Habitacion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Habitacion>();
        for (int i = 0; i < 10; i++) {
            Habitacion obj = getNewTransientHabitacion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
