// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Habitacion;
import es.uca.iw.hoteloasis.domain.HabitacionDataOnDemand;
import es.uca.iw.hoteloasis.domain.HabitacionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HabitacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HabitacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HabitacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HabitacionIntegrationTest: @Transactional;
    
    @Autowired
    HabitacionDataOnDemand HabitacionIntegrationTest.dod;
    
    @Test
    public void HabitacionIntegrationTest.testCountHabitacions() {
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", dod.getRandomHabitacion());
        long count = Habitacion.countHabitacions();
        Assert.assertTrue("Counter for 'Habitacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HabitacionIntegrationTest.testFindHabitacion() {
        Habitacion obj = dod.getRandomHabitacion();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to provide an identifier", id);
        obj = Habitacion.findHabitacion(id);
        Assert.assertNotNull("Find method for 'Habitacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Habitacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HabitacionIntegrationTest.testFindAllHabitacions() {
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", dod.getRandomHabitacion());
        long count = Habitacion.countHabitacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Habitacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Habitacion> result = Habitacion.findAllHabitacions();
        Assert.assertNotNull("Find all method for 'Habitacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Habitacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HabitacionIntegrationTest.testFindHabitacionEntries() {
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", dod.getRandomHabitacion());
        long count = Habitacion.countHabitacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Habitacion> result = Habitacion.findHabitacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Habitacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Habitacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HabitacionIntegrationTest.testFlush() {
        Habitacion obj = dod.getRandomHabitacion();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to provide an identifier", id);
        obj = Habitacion.findHabitacion(id);
        Assert.assertNotNull("Find method for 'Habitacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHabitacion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Habitacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HabitacionIntegrationTest.testMergeUpdate() {
        Habitacion obj = dod.getRandomHabitacion();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to provide an identifier", id);
        obj = Habitacion.findHabitacion(id);
        boolean modified =  dod.modifyHabitacion(obj);
        Integer currentVersion = obj.getVersion();
        Habitacion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Habitacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HabitacionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", dod.getRandomHabitacion());
        Habitacion obj = dod.getNewTransientHabitacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Habitacion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Habitacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HabitacionIntegrationTest.testRemove() {
        Habitacion obj = dod.getRandomHabitacion();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Habitacion' failed to provide an identifier", id);
        obj = Habitacion.findHabitacion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Habitacion' with identifier '" + id + "'", Habitacion.findHabitacion(id));
    }
    
}
