// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Hotel;
import es.uca.iw.hoteloasis.domain.HotelDataOnDemand;
import es.uca.iw.hoteloasis.domain.HotelIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HotelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HotelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HotelIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HotelIntegrationTest: @Transactional;
    
    @Autowired
    HotelDataOnDemand HotelIntegrationTest.dod;
    
    @Test
    public void HotelIntegrationTest.testCountHotels() {
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", dod.getRandomHotel());
        long count = Hotel.countHotels();
        Assert.assertTrue("Counter for 'Hotel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HotelIntegrationTest.testFindHotel() {
        Hotel obj = dod.getRandomHotel();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to provide an identifier", id);
        obj = Hotel.findHotel(id);
        Assert.assertNotNull("Find method for 'Hotel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Hotel' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HotelIntegrationTest.testFindAllHotels() {
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", dod.getRandomHotel());
        long count = Hotel.countHotels();
        Assert.assertTrue("Too expensive to perform a find all test for 'Hotel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Hotel> result = Hotel.findAllHotels();
        Assert.assertNotNull("Find all method for 'Hotel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Hotel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HotelIntegrationTest.testFindHotelEntries() {
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", dod.getRandomHotel());
        long count = Hotel.countHotels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Hotel> result = Hotel.findHotelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Hotel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Hotel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HotelIntegrationTest.testFlush() {
        Hotel obj = dod.getRandomHotel();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to provide an identifier", id);
        obj = Hotel.findHotel(id);
        Assert.assertNotNull("Find method for 'Hotel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHotel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Hotel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HotelIntegrationTest.testMergeUpdate() {
        Hotel obj = dod.getRandomHotel();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to provide an identifier", id);
        obj = Hotel.findHotel(id);
        boolean modified =  dod.modifyHotel(obj);
        Integer currentVersion = obj.getVersion();
        Hotel merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Hotel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HotelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", dod.getRandomHotel());
        Hotel obj = dod.getNewTransientHotel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Hotel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Hotel' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Hotel' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HotelIntegrationTest.testRemove() {
        Hotel obj = dod.getRandomHotel();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hotel' failed to provide an identifier", id);
        obj = Hotel.findHotel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Hotel' with identifier '" + id + "'", Hotel.findHotel(id));
    }
    
}
