// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.EstanciaDataOnDemand;
import es.uca.iw.hoteloasis.domain.Llamada;
import es.uca.iw.hoteloasis.domain.LlamadaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LlamadaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LlamadaDataOnDemand: @Component;
    
    private Random LlamadaDataOnDemand.rnd = new SecureRandom();
    
    private List<Llamada> LlamadaDataOnDemand.data;
    
    @Autowired
    EstanciaDataOnDemand LlamadaDataOnDemand.estanciaDataOnDemand;
    
    public Llamada LlamadaDataOnDemand.getNewTransientLlamada(int index) {
        Llamada obj = new Llamada();
        setMinutos_internacionales(obj, index);
        setMinutos_internet(obj, index);
        setMinutos_nacionales(obj, index);
        return obj;
    }
    
    public void LlamadaDataOnDemand.setMinutos_internacionales(Llamada obj, int index) {
        double minutos_internacionales = new Integer(index).doubleValue();
        obj.setMinutos_internacionales(minutos_internacionales);
    }
    
    public void LlamadaDataOnDemand.setMinutos_internet(Llamada obj, int index) {
        double minutos_internet = new Integer(index).doubleValue();
        obj.setMinutos_internet(minutos_internet);
    }
    
    public void LlamadaDataOnDemand.setMinutos_nacionales(Llamada obj, int index) {
        double minutos_nacionales = new Integer(index).doubleValue();
        obj.setMinutos_nacionales(minutos_nacionales);
    }
    
    public Llamada LlamadaDataOnDemand.getSpecificLlamada(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Llamada obj = data.get(index);
        Long id = obj.getId();
        return Llamada.findLlamada(id);
    }
    
    public Llamada LlamadaDataOnDemand.getRandomLlamada() {
        init();
        Llamada obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Llamada.findLlamada(id);
    }
    
    public boolean LlamadaDataOnDemand.modifyLlamada(Llamada obj) {
        return false;
    }
    
    public void LlamadaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Llamada.findLlamadaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Llamada' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Llamada>();
        for (int i = 0; i < 10; i++) {
            Llamada obj = getNewTransientLlamada(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
