// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Llamada;
import es.uca.iw.hoteloasis.domain.LlamadaDataOnDemand;
import es.uca.iw.hoteloasis.domain.LlamadaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LlamadaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LlamadaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LlamadaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LlamadaIntegrationTest: @Transactional;
    
    @Autowired
    LlamadaDataOnDemand LlamadaIntegrationTest.dod;
    
    @Test
    public void LlamadaIntegrationTest.testCountLlamadas() {
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", dod.getRandomLlamada());
        long count = Llamada.countLlamadas();
        Assert.assertTrue("Counter for 'Llamada' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LlamadaIntegrationTest.testFindLlamada() {
        Llamada obj = dod.getRandomLlamada();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to provide an identifier", id);
        obj = Llamada.findLlamada(id);
        Assert.assertNotNull("Find method for 'Llamada' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Llamada' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LlamadaIntegrationTest.testFindAllLlamadas() {
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", dod.getRandomLlamada());
        long count = Llamada.countLlamadas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Llamada', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Llamada> result = Llamada.findAllLlamadas();
        Assert.assertNotNull("Find all method for 'Llamada' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Llamada' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LlamadaIntegrationTest.testFindLlamadaEntries() {
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", dod.getRandomLlamada());
        long count = Llamada.countLlamadas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Llamada> result = Llamada.findLlamadaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Llamada' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Llamada' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LlamadaIntegrationTest.testFlush() {
        Llamada obj = dod.getRandomLlamada();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to provide an identifier", id);
        obj = Llamada.findLlamada(id);
        Assert.assertNotNull("Find method for 'Llamada' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLlamada(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Llamada' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LlamadaIntegrationTest.testMergeUpdate() {
        Llamada obj = dod.getRandomLlamada();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to provide an identifier", id);
        obj = Llamada.findLlamada(id);
        boolean modified =  dod.modifyLlamada(obj);
        Integer currentVersion = obj.getVersion();
        Llamada merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Llamada' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LlamadaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", dod.getRandomLlamada());
        Llamada obj = dod.getNewTransientLlamada(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Llamada' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Llamada' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Llamada' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LlamadaIntegrationTest.testRemove() {
        Llamada obj = dod.getRandomLlamada();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Llamada' failed to provide an identifier", id);
        obj = Llamada.findLlamada(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Llamada' with identifier '" + id + "'", Llamada.findLlamada(id));
    }
    
}
