// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Minibar;
import es.uca.iw.hoteloasis.domain.MinibarDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MinibarDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MinibarDataOnDemand: @Component;
    
    private Random MinibarDataOnDemand.rnd = new SecureRandom();
    
    private List<Minibar> MinibarDataOnDemand.data;
    
    public Minibar MinibarDataOnDemand.getNewTransientMinibar(int index) {
        Minibar obj = new Minibar();
        setNombre(obj, index);
        return obj;
    }
    
    public void MinibarDataOnDemand.setNombre(Minibar obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Minibar MinibarDataOnDemand.getSpecificMinibar(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Minibar obj = data.get(index);
        Long id = obj.getId();
        return Minibar.findMinibar(id);
    }
    
    public Minibar MinibarDataOnDemand.getRandomMinibar() {
        init();
        Minibar obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Minibar.findMinibar(id);
    }
    
    public boolean MinibarDataOnDemand.modifyMinibar(Minibar obj) {
        return false;
    }
    
    public void MinibarDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Minibar.findMinibarEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Minibar' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Minibar>();
        for (int i = 0; i < 10; i++) {
            Minibar obj = getNewTransientMinibar(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
