// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Minibar;
import es.uca.iw.hoteloasis.domain.MinibarDataOnDemand;
import es.uca.iw.hoteloasis.domain.MinibarIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MinibarIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MinibarIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MinibarIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MinibarIntegrationTest: @Transactional;
    
    @Autowired
    MinibarDataOnDemand MinibarIntegrationTest.dod;
    
    @Test
    public void MinibarIntegrationTest.testCountMinibars() {
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", dod.getRandomMinibar());
        long count = Minibar.countMinibars();
        Assert.assertTrue("Counter for 'Minibar' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MinibarIntegrationTest.testFindMinibar() {
        Minibar obj = dod.getRandomMinibar();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to provide an identifier", id);
        obj = Minibar.findMinibar(id);
        Assert.assertNotNull("Find method for 'Minibar' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Minibar' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MinibarIntegrationTest.testFindAllMinibars() {
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", dod.getRandomMinibar());
        long count = Minibar.countMinibars();
        Assert.assertTrue("Too expensive to perform a find all test for 'Minibar', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Minibar> result = Minibar.findAllMinibars();
        Assert.assertNotNull("Find all method for 'Minibar' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Minibar' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MinibarIntegrationTest.testFindMinibarEntries() {
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", dod.getRandomMinibar());
        long count = Minibar.countMinibars();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Minibar> result = Minibar.findMinibarEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Minibar' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Minibar' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MinibarIntegrationTest.testFlush() {
        Minibar obj = dod.getRandomMinibar();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to provide an identifier", id);
        obj = Minibar.findMinibar(id);
        Assert.assertNotNull("Find method for 'Minibar' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMinibar(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Minibar' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MinibarIntegrationTest.testMergeUpdate() {
        Minibar obj = dod.getRandomMinibar();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to provide an identifier", id);
        obj = Minibar.findMinibar(id);
        boolean modified =  dod.modifyMinibar(obj);
        Integer currentVersion = obj.getVersion();
        Minibar merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Minibar' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MinibarIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", dod.getRandomMinibar());
        Minibar obj = dod.getNewTransientMinibar(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Minibar' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Minibar' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Minibar' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MinibarIntegrationTest.testRemove() {
        Minibar obj = dod.getRandomMinibar();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar' failed to provide an identifier", id);
        obj = Minibar.findMinibar(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Minibar' with identifier '" + id + "'", Minibar.findMinibar(id));
    }
    
}
