// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Minibar_bebida;
import es.uca.iw.hoteloasis.domain.Minibar_bebidaDataOnDemand;
import es.uca.iw.hoteloasis.domain.Minibar_bebidaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Minibar_bebidaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: Minibar_bebidaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: Minibar_bebidaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: Minibar_bebidaIntegrationTest: @Transactional;
    
    @Autowired
    Minibar_bebidaDataOnDemand Minibar_bebidaIntegrationTest.dod;
    
    @Test
    public void Minibar_bebidaIntegrationTest.testCountMinibar_bebidas() {
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", dod.getRandomMinibar_bebida());
        long count = Minibar_bebida.countMinibar_bebidas();
        Assert.assertTrue("Counter for 'Minibar_bebida' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testFindMinibar_bebida() {
        Minibar_bebida obj = dod.getRandomMinibar_bebida();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to provide an identifier", id);
        obj = Minibar_bebida.findMinibar_bebida(id);
        Assert.assertNotNull("Find method for 'Minibar_bebida' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Minibar_bebida' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testFindAllMinibar_bebidas() {
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", dod.getRandomMinibar_bebida());
        long count = Minibar_bebida.countMinibar_bebidas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Minibar_bebida', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Minibar_bebida> result = Minibar_bebida.findAllMinibar_bebidas();
        Assert.assertNotNull("Find all method for 'Minibar_bebida' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Minibar_bebida' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testFindMinibar_bebidaEntries() {
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", dod.getRandomMinibar_bebida());
        long count = Minibar_bebida.countMinibar_bebidas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Minibar_bebida> result = Minibar_bebida.findMinibar_bebidaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Minibar_bebida' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Minibar_bebida' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testFlush() {
        Minibar_bebida obj = dod.getRandomMinibar_bebida();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to provide an identifier", id);
        obj = Minibar_bebida.findMinibar_bebida(id);
        Assert.assertNotNull("Find method for 'Minibar_bebida' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMinibar_bebida(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Minibar_bebida' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testMergeUpdate() {
        Minibar_bebida obj = dod.getRandomMinibar_bebida();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to provide an identifier", id);
        obj = Minibar_bebida.findMinibar_bebida(id);
        boolean modified =  dod.modifyMinibar_bebida(obj);
        Integer currentVersion = obj.getVersion();
        Minibar_bebida merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Minibar_bebida' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", dod.getRandomMinibar_bebida());
        Minibar_bebida obj = dod.getNewTransientMinibar_bebida(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Minibar_bebida' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Minibar_bebida' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void Minibar_bebidaIntegrationTest.testRemove() {
        Minibar_bebida obj = dod.getRandomMinibar_bebida();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Minibar_bebida' failed to provide an identifier", id);
        obj = Minibar_bebida.findMinibar_bebida(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Minibar_bebida' with identifier '" + id + "'", Minibar_bebida.findMinibar_bebida(id));
    }
    
}
