// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Tarifa;
import es.uca.iw.hoteloasis.domain.TarifaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TarifaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TarifaDataOnDemand: @Component;
    
    private Random TarifaDataOnDemand.rnd = new SecureRandom();
    
    private List<Tarifa> TarifaDataOnDemand.data;
    
    public Tarifa TarifaDataOnDemand.getNewTransientTarifa(int index) {
        Tarifa obj = new Tarifa();
        setCoste(obj, index);
        setServicio(obj, index);
        return obj;
    }
    
    public void TarifaDataOnDemand.setCoste(Tarifa obj, int index) {
        double coste = new Integer(index).doubleValue();
        obj.setCoste(coste);
    }
    
    public void TarifaDataOnDemand.setServicio(Tarifa obj, int index) {
        String servicio = "servicio_" + index;
        obj.setServicio(servicio);
    }
    
    public Tarifa TarifaDataOnDemand.getSpecificTarifa(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tarifa obj = data.get(index);
        Long id = obj.getId();
        return Tarifa.findTarifa(id);
    }
    
    public Tarifa TarifaDataOnDemand.getRandomTarifa() {
        init();
        Tarifa obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Tarifa.findTarifa(id);
    }
    
    public boolean TarifaDataOnDemand.modifyTarifa(Tarifa obj) {
        return false;
    }
    
    public void TarifaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Tarifa.findTarifaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tarifa' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tarifa>();
        for (int i = 0; i < 10; i++) {
            Tarifa obj = getNewTransientTarifa(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
