// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Hotel;
import es.uca.iw.hoteloasis.domain.Tarifa;
import es.uca.iw.hoteloasis.domain.TarifaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TarifaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TarifaDataOnDemand: @Component;
    
    private Random TarifaDataOnDemand.rnd = new SecureRandom();
    
    private List<Tarifa> TarifaDataOnDemand.data;
    
    public Tarifa TarifaDataOnDemand.getNewTransientTarifa(int index) {
        Tarifa obj = new Tarifa();
        setCancel_dos_cinco_dias(obj, index);
        setCancel_mas_cinco_dias(obj, index);
        setCancel_mismo_dia(obj, index);
        setCancel_uno_dos_dias(obj, index);
        setHotel(obj, index);
        setInternet(obj, index);
        setLlamada_internacional(obj, index);
        setLlamada_nacional(obj, index);
        return obj;
    }
    
    public void TarifaDataOnDemand.setCancel_dos_cinco_dias(Tarifa obj, int index) {
        double cancel_dos_cinco_dias = new Integer(index).doubleValue();
        obj.setCancel_dos_cinco_dias(cancel_dos_cinco_dias);
    }
    
    public void TarifaDataOnDemand.setCancel_mas_cinco_dias(Tarifa obj, int index) {
        double cancel_mas_cinco_dias = new Integer(index).doubleValue();
        obj.setCancel_mas_cinco_dias(cancel_mas_cinco_dias);
    }
    
    public void TarifaDataOnDemand.setCancel_mismo_dia(Tarifa obj, int index) {
        double cancel_mismo_dia = new Integer(index).doubleValue();
        obj.setCancel_mismo_dia(cancel_mismo_dia);
    }
    
    public void TarifaDataOnDemand.setCancel_uno_dos_dias(Tarifa obj, int index) {
        double cancel_uno_dos_dias = new Integer(index).doubleValue();
        obj.setCancel_uno_dos_dias(cancel_uno_dos_dias);
    }
    
    public void TarifaDataOnDemand.setHotel(Tarifa obj, int index) {
        Hotel hotel = null;
        obj.setHotel(hotel);
    }
    
    public void TarifaDataOnDemand.setInternet(Tarifa obj, int index) {
        double internet = new Integer(index).doubleValue();
        obj.setInternet(internet);
    }
    
    public void TarifaDataOnDemand.setLlamada_internacional(Tarifa obj, int index) {
        double llamada_internacional = new Integer(index).doubleValue();
        obj.setLlamada_internacional(llamada_internacional);
    }
    
    public void TarifaDataOnDemand.setLlamada_nacional(Tarifa obj, int index) {
        double llamada_nacional = new Integer(index).doubleValue();
        obj.setLlamada_nacional(llamada_nacional);
    }
    
    public Tarifa TarifaDataOnDemand.getSpecificTarifa(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tarifa obj = data.get(index);
        Long id = obj.getId();
        return Tarifa.findTarifa(id);
    }
    
    public Tarifa TarifaDataOnDemand.getRandomTarifa() {
        init();
        Tarifa obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Tarifa.findTarifa(id);
    }
    
    public boolean TarifaDataOnDemand.modifyTarifa(Tarifa obj) {
        return false;
    }
    
    public void TarifaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Tarifa.findTarifaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tarifa' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tarifa>();
        for (int i = 0; i < 10; i++) {
            Tarifa obj = getNewTransientTarifa(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
