// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Minibar;

privileged aspect Minibar_Roo_JavaBean {
    
    public String Minibar.getNombre() {
        return this.nombre;
    }
    
    public void Minibar.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
