// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.hoteloasis.domain;

import es.uca.iw.hoteloasis.domain.Rol;

privileged aspect Rol_Roo_JavaBean {
    
    public String Rol.getNombre() {
        return this.nombre;
    }
    
    public void Rol.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
